//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooClinic.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooClinicEntities : DbContext
    {
        public ZooClinicEntities()
            : base("name=ZooClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animals> Animals { get; set; }
        public virtual DbSet<Appointments> Appointments { get; set; }
        public virtual DbSet<Breeds> Breeds { get; set; }
        public virtual DbSet<Owners> Owners { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Veterinarians> Veterinarians { get; set; }
    }
}
