//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooClinic.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccinations
    {
        public int ID { get; set; }
        public Nullable<int> AnimalID { get; set; }
        public Nullable<System.DateTime> VaccinationDate { get; set; }
        public string VaccinationType { get; set; }
    
        public virtual Animals Animals { get; set; }
    }
}
